blank_issues_enabled: false

contact_links:
  - name: Discussion ğŸ’¡
    url: https://github.com/minimit/xtendui/discussions/new
    about: If you have a ideas or need help use the dicussion forums
  - name: Docs and FAQS ğŸ“
    url: https://xtendui.com/
    about: Check out the docs for answers to common questions
